version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: db-eco
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - notification-eco
  redis:
    image: redis:latest
    container_name: redis-eco
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  api-clima:
    build: ./api-clima
    container_name: api-clima-eco
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./api-clima:/go/src/
    depends_on:
      - mysql
    networks:
      - notification-eco

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
networks:
  notification-eco:
    driver: bridge